packages:
  - workflow
  - model
  - ui
  - block

catalog:
  "@platforma-sdk/model": ^1.45.0
  "@platforma-sdk/ui-vue": ^1.45.5
  "@platforma-sdk/workflow-tengo": ^5.5.9
  "@platforma-sdk/block-tools": ^2.6.16
  "@platforma-sdk/test": ^1.45.11
  "@platforma-sdk/tengo-builder": ^2.3.3
  "@platforma-sdk/package-builder": ^3.10.6
  "@milaboratories/graph-maker": ^1.1.175
  "@platforma-sdk/eslint-config": ^1.1.0

  "@platforma-open/milaboratories.runenv-python-3": ^3.12.6
  "@milaboratories/software-pframes-conv": ^2.2.9
  "@platforma-open/milaboratories.software-small-binaries": ^1.15.23
  "@platforma-open/milaboratories.software-ptransform": ^1.6.6
  "@platforma-open/immunewatch.software-detect": 4.0.4

  'ag-grid-enterprise': &ag-grid ^34.3.1
  'ag-grid-vue3': *ag-grid

  "vue": ^3.5.12
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.5.2

  "vite": ^6.3.3
  "vitest": ^2.1.4
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.29.7
  "js-yaml": ^4.1.0

  "zod": ^3.23.8
